export const BASKET_ADD_REQUEST = 'BASKET_ADD_REQUEST'
export const BASKET_ADD_SUCCESS = 'BASKET_ADD_SUCCESS'
export const BASKET_ADD_FAIL = 'BASKET_ADD_FAIL'

export const BASKET_REMOVE_REQUEST = 'BASKET_REMOVE_REQUEST'
export const BASKET_REMOVE_SUCCESS = 'BASKET_REMOVE_SUCCESS'
export const BASKET_REMOVE_FAIL = 'BASKET_REMOVE_FAIL'

export const BASKET_REMOVE_AFTER_PAID = "BASKET_REMOVE_AFTER_PAID"