export const PRODUCT_CREATE_IMAGE_REQUEST = 'PRODUCT_CREATE_IMAGE_REQUEST'
export const PRODUCT_CREATE_IMAGE_SUCCESS = 'PRODUCT_CREATE_IMAGE_SUCCESS'
export const PRODUCT_CREATE_IMAGE_FAIL = 'PRODUCT_CREATE_IMAGE_FAIL'